language: r
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

warnings_are_errors: true

# before_deploy: Rscript -e 'remotes::install_cran("pkgdown");remotes::install_github("ropensci/rotemplate")'
# deploy:
#   provider: script
#   script: Rscript -e 'pkgdown::deploy_site_github()'
#   skip_cleanup: true

notifications:
    email:
      on_success: change
      on_failure: change
