# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coord_matches <- function(sldf, tolval = 0.000) {
    .Call('_stplanrlite_coord_matches', PACKAGE = 'stplanrlite', sldf, tolval)
}

join_spatiallines_coords <- function(sldf, startx, starty) {
    .Call('_stplanrlite_join_spatiallines_coords', PACKAGE = 'stplanrlite', sldf, startx, starty)
}

coord_matches_sf <- function(x, sortedx, sllength, tolval = 0.000) {
    .Call('_stplanrlite_coord_matches_sf', PACKAGE = 'stplanrlite', x, sortedx, sllength, tolval)
}

join_spatiallines_coords_sf <- function(lines, startx, starty) {
    .Call('_stplanrlite_join_spatiallines_coords_sf', PACKAGE = 'stplanrlite', lines, startx, starty)
}

